/*
 *
 * DelistContainer constants
 *
 */

export const DEFAULT_ACTION = 'app/DelistContainer/DEFAULT_ACTION';
export const API_FETCH = 'app/DelistContainer/API_FETCH';
export const API_FETCH_SUCCESS = 'app/DelistContainer/API_FETCH_SUCCESS';
export const DATA_URL_PARAMS = 'app/DelistContainer/DATA_URL_PARAMS';

//WEEK TAB STRING
export const WEEK_URL = 'app/DelistContainer/WEEK_URL';
//STORE TAB STRING
export const STORE_URL = 'app/DelistContainer/STORE_URL';

export const TABLE_DATA_FETCH = 'app/DelistContainer/TABLE_DATA_FETCH';
export const TABLE_DATA_FETCH_SUCCESS = 'app/DelistContainer/TABLE_DATA_FETCH_SUCCESS';
export const SUBSTITUTE_DATA_URL = 'app/DelistContainer/SUBSTITUTE_DATA_URL';
export const SUBSTITUTE_DATA_LONG_DESC = 'app/DelistContainer/SUBSTITUTE_DATA_LONG_DESC';
export const SUBSTITUTE_DATA_URL_SUCCESS = 'app/DelistContainer/SUBSTITUTE_DATA_URL_SUCCESS';
export const WATERFALL_VALUE = 'app/DelistContainer/WATERFALL_VALUE';
export const WATERFALL_VALUE_SUCCESS = 'app/DelistContainer/WATERFALL_VALUE_SUCCESS';
export const GENERATE_URL_PARAMS_DATA = 'app/DelistContainer/GENERATE_URL_PARAMS_DATA';

export const GENERATE_URL_PARAMS_DATA_SUCCESS = 'app/DelistContainer/GENERATE_URL_PARAMS_DATA_SUCCESS';

//URL PARAMS
export const URL_PARAMS = 'app/DelistContainer/URL_PARAMS';

export const SUPPLIER_POPUP_TABLE_DATA_FETCH_SUCCESS = 'app/DelistContainer/SUPPLIER_POPUP_TABLE_DATA_FETCH_SUCCESS';

// DELIST POPUP TABLE
export const DELIST_POPUP_TABLE_DATA_FETCH_SUCCESS = 'app/DelistContainer/DELIST_POPUP_TABLE_DATA_FETCH_SUCCESS';

//SUPPLIER PAGINATION TABLE
export const SUPPLIER_PAGINATION_DATA = 'app/DelistContainer/SUPPLIER_PAGINATION_DATA';

//SUPPLIER POPUP PAGINATION TABLE
export const SUPPLIER_POPUP_PAGINATION_DATA = 'app/DelistContainer/SUPPLIER_POPUP_PAGINATION_DATA';

//DELIST PAGINATION TABLE
export const DELIST_PAGINATION_DATA = 'app/DelistContainer/DELIST_PAGINATION_DATA';

//DELIST POPUP PAGINATION TABLE
export const DELIST_POPUP_PAGINATION_DATA = 'app/DelistContainer/DELIST_POPUP_PAGINATION_DATA';

//TABLE TYPE
export const TABLE_TYPE = 'app/DelistContainer/TABLE_TYPE';

//SEARCH - SUPPLIER TABLE
export const SEARCH_SUPPLIER_TABLE = 'app/DelistContainer/SEARCH_SUPPLIER_TABLE';

//SEARCH - DELIST TABLE
export const SEARCH_DELIST_TABLE = 'app/DelistContainer/SEARCH_DELIST_TABLE';

//BREADCRUMB - WEEK
export const WEEK_BREADCRUMB = 'app/DelistContainer/WEEK_BREADCRUMB';

//BREADCRUMB - STORE
export const STORE_BREADCRUMB = 'app/DelistContainer/STORE_BREADCRUMB';

//DELIST TABLE
export const DELIST_TABLE = 'app/DelistContainer/DELIST_TABLE';

//SIDE FILTER RESET
export const SIDE_FILTER_RESET = 'app/DelistContainer/SIDE_FILTER_RESET';

//DELIST TABLE SUCCESS
export const DELIST_TABLE_SUCCESS = 'app/DelistContainer/DELIST_TABLE_SUCCESS';

// SUPPLIER POPUP TABLE
export const SUPPLIER_IMPACT_TABLE_DATA_URL = 'app/DelistContainer/SUPPLIER_IMPACT_TABLE_DATA_URL';
export const SUPPLIER_IMPACT_TABLE_DATA_URL_SUCCESS = 'app/DelistContainer/SUPPLIER_IMPACT_TABLE_DATA_URL_SUCCESS';

export const GENERATE_TABLE = 'app/DelistContainer/GENERATE_TABLE';
export const GENERATE_TABLE_SUCCESS = 'app/DelistContainer/GENERATE_TABLE_SUCCESS';
export const GENERATE_SIDE_FILTER = 'app/DelistContainer/GENERATE_SIDE_FILTER';
export const GENERATE_SIDE_FILTER_SUCCESS = 'app/DelistContainer/GENERATE_SIDE_FILTER_SUCCESS';
export const GENERATE_URL_PARAMS = 'app/DelistContainer/GENERATE_URL_PARAMS';
export const GENERATE_URL_PARAMS_STRING = 'app/DelistContainer/GENERATE_URL_PARAMS_STRING';
export const WATERFALL_SPINNER_SUCCESS = 'app/DelistContainer/WATERFALL_SPINNER_SUCCESS';
export const WATERFALL_PROFIT_SPINNER_SUCCESS = 'app/DelistContainer/WATERFALL_PROFIT_SPINNER_SUCCESS';
export const SUPPLIER_IMPACT_SPINNER_SUCCESS = 'app/DelistContainer/SUPPLIER_IMPACT_SPINNER_SUCCESS';
export const DELIST_PRODUCT_SPINNER_SUCCESS = 'app/DelistContainer/DELIST_PRODUCT_SPINNER_SUCCESS';



//WATERFALL SPINNER STARTED
export const SPINNER_STARTED = 'app/DelistContainer/SPINNER_STARTED';


export const GENERATE_FILTER_PARAMS_STRING = 'app/DelistContainer/GENERATE_FILTER_PARAMS_STRING';


export const GENERATE_URL_PARAMS_DATA_STRING = 'app/DelistContainer/GENERATE_URL_PARAMS_DATA_STRING';

export const GENERATE_URL_PARAMS_DATA2 = 'app/DelistContainer/GENERATE_URL_PARAMS_DATA2';
export const GENERATE_URL_PARAMS_DATA2_STRING = 'app/DelistContainer/GENERATE_URL_PARAMS_DATA2_STRING';


//FILTERS - APPLY BUTTON CLICK
export const APPLY_BTN_CLICK = 'app/DelistContainer/APPLY_BTN_CLICK';

//TESTING AJAX CALLS
export const TEST_AJAX = 'app/DelistContainer/TEST_AJAX';
export const TEST_AJAX_SUCCESS = 'app/DelistContainer/TEST_AJAX_SUCCESS';
